IF DB_ID('TaiPlay') IS NULL
	CREATE DATABASE TaiPlay;
go

USE TaiPlay;
go

CREATE TABLE Trip(
	TripId INT IDENTITY(1,1) NOT NULL, CONSTRAINT PK_TripId PRIMARY KEY (TripId),
	UserId INT NOT NULL, 
	ImageUrl NVARCHAR(2000) NULL,
	TripName NVARCHAR(100)NOT NULL,
	Description NVARCHAR(500)NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Trip_CreatedAt DEFAULT SYSUTCDATETIME(),
	UpdatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Trip_UpdatedAt DEFAULT SYSUTCDATETIME()
);

CREATE TABLE TripItem(
	TripItemId INT IDENTITY(1,1) NOT NULL, CONSTRAINT PK_TripItemId PRIMARY KEY(TripItemId),
	TripId INT NOT NULL, 
	Title NVARCHAR(100) NULL,
	Description NVARCHAR(500) NULL,
	Day INT NOT NULL,
	AttractionId INT NOT NULL,
	SortOrder INT NOT NULL,
	TransportationId INT NULL,
	CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_TripItem_CreatedAt DEFAULT SYSUTCDATETIME(),
	UpdatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_TripItem_UpdatedAt DEFAULT SYSUTCDATETIME(),
);

CREATE TABLE TripRoute(
	TripRouteId INT IDENTITY(1,1) NOT NULL, CONSTRAINT PK_TripRouteId PRIMARY KEY(TripRouteId),
	StartItemId INT NOT NULL,
	EndItemId INT NOT NULL,
	TransportationId INT NOT NULL,  --TODO:待更新, 串TripTransportation
	CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_TripRoute_CreatedAt DEFAULT SYSUTCDATETIME(),
	UpdatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_TripRoute_UpdatedAt DEFAULT SYSUTCDATETIME(),
);

CREATE TABLE TripTransportation(
	TransportationId INT IDENTITY(1,1) NOT NULL, CONSTRAINT PK_Transportation PRIMARY KEY(TransportationId),
	ImageUrl NVARCHAR(500) NOT NULL,
	Name NVARCHAR(100)NOT NULL,
	CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_TripTransportation_CreatedAt DEFAULT SYSUTCDATETIME(),
	UpdatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_TripTransportation_UpdatedAt DEFAULT SYSUTCDATETIME(),
	IsActive bit NOT NULL CONSTRAINT DF_TripTransportation_IsActive DEFAULT 1
);

ALTER TABLE TripItem ADD CONSTRAINT FK_TripItem_AttractionId FOREIGN KEY(TripId) REFERENCES Attractions(AttractionId);
ALTER TABLE TripItem ADD CONSTRAINT FK_TripItem_TripId FOREIGN KEY(TripId) REFERENCES Trip(TripId);

ALTER TABLE TripRoute ADD CONSTRAINT FK_TripRoute_StartItemId FOREIGN KEY(StartItemId) REFERENCES TripItem(TripItemId);
ALTER TABLE TripRoute ADD CONSTRAINT FK_TripRoute_EndItemId FOREIGN KEY (EndItemId) REFERENCES TripItem(TripItemId);