use TaiPlay;

CREATE TABLE MapType(
	TypeId INT IDENTITY(1,1) NOT NULL, CONSTRAINT PK_MapTypeId PRIMARY KEY(TypeId),
	TypeName NVARCHAR(100) NOT NULL,
	ImageUrl NVARCHAR(2000) NOT NULL,
	IsActive BIT NOT NULL CONSTRAINT DF_MapType_IsActive DEFAULT 1
);